### ISSUE TITLE
Move to nats-py 2.6.0

### ISSUE THREAD

**Issue by kirill-ratkin** [lwinterface/panini#282]
Hi.

There is issue in nats-py==2.2.0 and we discussing it in this thread: https://github.com/nats-io/nats.py/issues/517
I opened this thread because `pip install panini` returns error. 

Here it is:
```
$ pip install panini
Collecting panini
  Downloading panini-0.8.2-py3-none-any.whl.metadata (2.0 kB)
Collecting async-timeout==4.0.0 (from panini)
  Downloading async_timeout-4.0.0-py3-none-any.whl (6.1 kB)
Collecting nats-py==2.2.0 (from panini)
  Downloading nats-py-2.2.0.tar.gz (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      /tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `optional-dependencies` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `optional-dependencies = {'nkeys': ['nkeys']}`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `optional-dependencies` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `optional-dependencies` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      Traceback (most recent call last):
        File "/home/rukira/.temp/issues/3007/.venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/rukira/.temp/issues/3007/.venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/rukira/.temp/issues/3007/.venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 67, in apply_configuration
          return _apply(dist, config, filepath)
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
          _apply_project_table(dist, config, root_dir)
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 82, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-2ryr_cnr/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 223, in _optional_dependencies
          dist.extras_require = {**existing, **val}
      TypeError: 'list' object is not a mapping
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Python 3.8 and 3.9
OS: Cent OS Stream 9

I try to switch requirement to nats-py==2.6.0 and it seems panini works very well with it.
Could you see issue discussion in nats-py repository mentioned above and update requrements if you don't see reasons to stay on v2.2.0?

**Comment by artas728** [comment]
Hello @kirill-ratkin 

Thank you for this issue. We are aware of some compatibility concerns with the older version of nats-py. Based on your suggestion, we are now actively testing nats-py==2.6.0 with the latest Panini release (0.8.3b4) to ensure full compatibility and stability. This process is crucial to ensure that the upgrade does not introduce any new issues.

We aim to complete this testing promptly. Assuming no significant issues arise, we expect to release an updated version of Panini with nats-py==2.6.0 compatibility within the next few weeks.
