### ISSUE TITLE
slow customers 

### ISSUE THREAD

**Issue by oleksii-v** [lwinterface/panini#4]
anthill client get 'slow customer' error and disconnect from the server if internet get disconnected for few seconds.
Then an application is failed

```
Traceback (most recent call last):
  File "/Users/nelson/dev/ms_general2/strategy_liquidity_provider/run_euro.py", line 186, in <module>
    app.start()
  File "/Users/nelson/dev/ms_general2/anthill/app.py", line 181, in start
    self._start()
  File "/Users/nelson/dev/ms_general2/anthill/app.py", line 218, in _start
    self._start_tasks()
  File "/Users/nelson/dev/ms_general2/anthill/app.py", line 236, in _start_tasks
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError
```

**Comment by artas728** [comment]
I have tried to reproduce it, now when I turned off the internet I got no error(because NATS is trying to reconnect), but if there is no internet for a few minutes, I got:

`[Errno 51] Network is unreachable`
